version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/bot
    command: python -m bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app/bot
    logging:
      driver: json-file
      options:
        max-size: "900k"
        max-file: "10"
